---
name: locust
director_uuid: REPLACE_WITH_DIRECTOR_UUID

releases:
- {name: locust, version: latest}

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000

jobs:
- name: locust_master
  instances: 1
  templates:
  - {name: locust_master, release: locust}
  resource_pool: small
  networks:
  - default:
    - dns
    - gateway
    name: default
  - name: floating
    static_ips: [10.0.0.20]
- name: locust_slave
  instances: 3
  templates:
  - {name: locust_slave, release: locust}
  resource_pool: small
  networks:
  - name: default
